cr-manifest:
  - deploy/crds/open-enterprise-spinnaker_cr.yaml
#  - deploy/crds/deploy-oes.yaml
init-timeout: 60
csv-path: "deploy/olm-catalog/open-enterprise-spinnaker/1.17.4/open-enterprise-spinnaker.v1.17.4.clusterserviceversion.yaml"
