apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-service-settings-1.17.4
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
  gate.yml: |-
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
  {{- if .Values.halyard.repository }}
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.deck }}
  {{- else }}
    artifactId: {{ .Values.halyard.images.deck }}
  {{- end }}
    host: 0.0.0.0
  deck.yml: |-
    host: 0.0.0.0
  {{- if .Values.halyard.repository }}
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.deck }}
  {{- else }}
    artifactId: {{ .Values.halyard.images.deck }}
  {{- end }}
    env:
      API_HOST: http://spin-gate.{{ .Release.Namespace }}:8084
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
  {{- if .Values.halyard.repository }}
  front50.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.front50 }}
  fiat.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.fiat }}
  clouddriver.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.clouddriver }}
  orca.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.orca }}
  rosco.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.rosco }}
  igor.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.igor }}
  kayenta.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.kayenta }}
  echo.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.echo }}
  redis.yml: |-
    artifactId: {{ .Values.halyard.repository }}/{{ .Values.halyard.images.redis }}
    enabled: true
  {{- else }}
  front50.yml: |-
    artifactId: {{ .Values.halyard.images.front50 }}
  fiat.yml: |-
    artifactId: {{ .Values.halyard.images.fiat }}
  clouddriver.yml: |-
    artifactId: {{ .Values.halyard.images.clouddriver }}
  orca.yml: |-
    artifactId: {{ .Values.halyard.images.orca }}
  rosco.yml: |-
    artifactId: {{ .Values.halyard.images.rosco }}
  igor.yml: |-
    artifactId: {{ .Values.halyard.images.igor }}
  kayenta.yml: |-
    artifactId: {{ .Values.halyard.images.kayenta }}
  echo.yml: |-
    artifactId: {{ .Values.halyard.images.echo }}
  redis.yml: |-
    artifactId: {{ .Values.halyard.images.redis }}
    enabled: true
  {{- end }}
