apiVersion: v1
appVersion: version-09082019
description: Minio is a high performance distributed object storage server, designed
  for large-scale private cloud infrastructure.
home: https://minio.io
icon: https://www.minio.io/img/logo_160x160.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: Minio
name: minio
sources:
- https://github.com/minio/minio
version: version-09082019
