apiVersion: charts.helm.k8s.io/v1alpha1
kind: OpenEnterpriseSpinnakerOperator
metadata:
  name: oes
spec:
  halyard:
    spinnakerVersion: 1.16.0
    image:
      repository: devopsmx/ubi8-oes-operator-halyard
      tag: 1.16.0-2
  dockerRegistries:
    - name: dockerhub
      address: index.docker.io
      repositories:
        - library/alpine
        - library/ubuntu
        - library/centos
        - library/nginx
  spinnakerFeatureFlags:
    - artifacts
    - jobs
  minio:
    enabled: true
    persistence:
      enabled: false
  rbac:
    create: false
  serviceAccount:
    create: false
    halyardName: open-enterprise-spinnaker
    spinnakerName: null
