apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: opsmx-spinnaker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: opsmx-spinnaker-operator
  template:
    metadata:
      labels:
        name: opsmx-spinnaker-operator
    spec:
      serviceAccountName: opsmx-spinnaker-operator
      containers:
        - name: opsmx-spinnaker-operator
          # Replace this with the built image name
          image: zappo/spinnaker-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "opsmx-spinnaker-operator"
