apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-service-settings
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
  redis.yml: |-
    artifactId: opsmx11/operator-redis:v0.0.3
    enabled: true
  gate.yml: |-
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
    artifactId: opsmx11/operator-gate:v1.7.0
    host: 0.0.0.0
  deck.yml: |-
    host: 0.0.0.0
    artifactId: opsmx11/operator-deck:v2.6.1
    env:
      API_HOST: http://spin-gate.{{ .Release.Namespace }}:8084
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
  front50.yml: |-
    artifactId: opsmx11/operator-front50:v0.16.1
  fiat.yml: |-
    artifactId: opsmx11/operator-fiat:v1.4.0


