apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-service-settings
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
  redis.yml: |-
    artifactId: zappo/ubi8-redis:4.0.14
    enabled: true
  gate.yml: |-
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
    artifactId: zappo/ubi8-gate:master
    host: 0.0.0.0
  deck.yml: |-
    host: 0.0.0.0
    artifactId: zappo/ubi8-deck:master
    env:
      API_HOST: http://spin-gate.{{ .Release.Namespace }}:8084
    kubernetes:
    {{- if .Values.ingress.enabled }}
      useExecHealthCheck: false
      serviceType: NodePort
    {{- end }}
  front50.yml: |-
    artifactId: zappo/ubi8-os-front50:master
  fiat.yml: |-
    artifactId: zappo/ubi8-fiat:master
  clouddriver.yml: |-
    artifactId: zappo/ubi8-clouddriver:master
  echo.yml: |-
    artifactId: zappo/ubi8-echo:master
  igor.yml: |-
    artifactId: zappo/ubi8-igor:master
  rosco.yml: |-
    artifactId: zappo/ubi8-rosco:master
  orca.yml: |-
    artifactId: zappo/ubi8-orca:master
  kayenta.yml: |-
    artifactId: zappo/ubi8-kayenta:master
